import type { Metadata } from "next";
import "./globals.css";


// Metadatos de la aplicación
export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

// RootLayout con clases y fuentes aplicadas
export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
        <body
            className={` antialiased`}
        >
        {children}
        </body>
        </html>
    );
}
